package com.ram.adminlte.model;


import java.io.Serializable;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StateMaster generated by hbm2java
 */
@Entity
@Table(name = "StateMaster", catalog = "adminlte")
public class StateMaster implements Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer sid;
	
	private String name;
	
	public StateMaster() {
		// TODO Auto-generated constructor stub
	}

	public Integer getSid() {
		return sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public  String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "StateMaster [sid=" + sid + ", name=" + name + "]";
	}
	
	
	
	
	
}